# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'create_new_figure_dialog_UI.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QFrame, QGridLayout, QHBoxLayout, QLabel,
    QPushButton, QRadioButton, QSizePolicy, QVBoxLayout,
    QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(589, 292)
        self.gridLayout_6 = QGridLayout(Dialog)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.baseFrame = QFrame(Dialog)
        self.baseFrame.setObjectName(u"baseFrame")
        self.baseFrame.setFrameShape(QFrame.StyledPanel)
        self.baseFrame.setFrameShadow(QFrame.Raised)
        self.gridLayout = QGridLayout(self.baseFrame)
        self.gridLayout.setObjectName(u"gridLayout")
        self.frame_2 = QFrame(self.baseFrame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setMinimumSize(QSize(100, 100))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.classLayout = QVBoxLayout()
        self.classLayout.setSpacing(0)
        self.classLayout.setObjectName(u"classLayout")
        self.classTitle = QLabel(self.frame_2)
        self.classTitle.setObjectName(u"classTitle")
        self.classTitle.setMaximumSize(QSize(16777215, 25))
        self.classLayout.addWidget(self.classTitle)
        self.classCombo = QComboBox(self.frame_2)
        self.classCombo.addItem("")
        self.classCombo.addItem("")
        self.classCombo.addItem("")
        self.classCombo.setObjectName(u"classCombo")
        self.classLayout.addWidget(self.classCombo)
        self.verticalLayout.addLayout(self.classLayout)
        self.predQualLayout = QVBoxLayout()
        self.predQualLayout.setObjectName(u"predQualLayout")
        self.predQualTitle = QLabel(self.frame_2)
        self.predQualTitle.setObjectName(u"predQualTitle")
        self.predQualTitle.setMaximumSize(QSize(16777215, 25))
        self.predQualLayout.addWidget(self.predQualTitle)
        self.predQualCombo = QComboBox(self.frame_2)
        self.predQualCombo.addItem("")
        self.predQualCombo.addItem("")
        self.predQualCombo.addItem("")
        self.predQualCombo.addItem("")
        self.predQualCombo.addItem("")
        self.predQualCombo.setObjectName(u"predQualCombo")
        self.predQualLayout.addWidget(self.predQualCombo)
        self.verticalLayout.addLayout(self.predQualLayout)
        self.plotTypeLayout = QVBoxLayout()
        self.plotTypeLayout.setObjectName(u"plotTypeLayout")
        self.plotTypeTitle = QLabel(self.frame_2)
        self.plotTypeTitle.setObjectName(u"plotTypeTitle")
        self.plotTypeTitle.setMaximumSize(QSize(16777215, 25))
        self.plotTypeLayout.addWidget(self.plotTypeTitle)
        self.plotTypeCombo = QComboBox(self.frame_2)
        self.plotTypeCombo.addItem("")
        self.plotTypeCombo.addItem("")
        self.plotTypeCombo.addItem("")
        self.plotTypeCombo.setObjectName(u"plotTypeCombo")
        self.plotTypeLayout.addWidget(self.plotTypeCombo)
        self.verticalLayout.addLayout(self.plotTypeLayout)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")

        self.resetButton = QPushButton(self.baseFrame)
        self.resetButton.setObjectName(u"resetButton")
        self.horizontalLayout.addWidget(self.resetButton)
        self.cancelButton = QPushButton(self.baseFrame)
        self.cancelButton.setObjectName(u"cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.createButton = QPushButton(self.baseFrame)
        self.createButton.setObjectName(u"createButton")
        self.horizontalLayout.addWidget(self.createButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)

        self.baseFrame_2 = QFrame(self.baseFrame)
        self.baseFrame_2.setObjectName(u"baseFrame_2")
        self.baseFrame_2.setFrameShape(QFrame.StyledPanel)
        self.baseFrame_2.setFrameShadow(QFrame.Raised)
        self.gridLayout_2 = QGridLayout(self.baseFrame_2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.channelsFrame = QFrame(self.baseFrame_2)
        self.channelsFrame.setObjectName(u"channelsFrame")
        self.channelsFrame.setFrameShape(QFrame.StyledPanel)
        self.channelsFrame.setFrameShadow(QFrame.Raised)
        self.gridLayout_3 = QGridLayout(self.channelsFrame)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.channelsTitle = QLabel(self.channelsFrame)
        self.channelsTitle.setObjectName(u"channelsTitle")
        self.channelsTitle.setMaximumSize(QSize(16777215, 30))
        self.gridLayout_3.addWidget(self.channelsTitle, 0, 0, 1, 1)
        self.singleSampleCheckbox = QCheckBox(self.channelsFrame)
        self.singleSampleCheckbox.setObjectName(u"singleSampleCheckbox")
        self.gridLayout_3.addWidget(self.singleSampleCheckbox, 1, 0, 1, 1)
        self.averageSampleCheckbox = QCheckBox(self.channelsFrame)
        self.averageSampleCheckbox.setObjectName(u"averageSampleCheckbox")
        self.gridLayout_3.addWidget(self.averageSampleCheckbox, 2, 0, 1, 1)
        self.singleAnalyzerCheckbox = QCheckBox(self.channelsFrame)
        self.singleAnalyzerCheckbox.setObjectName(u"singleAnalyzerCheckbox")
        self.gridLayout_3.addWidget(self.singleAnalyzerCheckbox, 3, 0, 1, 1)
        self.averageAnalyzerCheckbox = QCheckBox(self.channelsFrame)
        self.averageAnalyzerCheckbox.setObjectName(u"averageAnalyzerCheckbox")
        self.gridLayout_3.addWidget(self.averageAnalyzerCheckbox, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.channelsFrame, 0, 0, 1, 1)
        self.radioFrame = QFrame(self.baseFrame_2)
        self.radioFrame.setObjectName(u"radioFrame")
        self.radioFrame.setFrameShape(QFrame.StyledPanel)
        self.radioFrame.setFrameShadow(QFrame.Raised)
        self.gridLayout_4 = QGridLayout(self.radioFrame)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.averageSampleFrame = QFrame(self.radioFrame)
        self.averageSampleFrame.setObjectName(u"averageSampleFrame")
        self.averageSampleFrame.setFrameShape(QFrame.StyledPanel)
        self.averageSampleFrame.setFrameShadow(QFrame.Raised)
        self.gridLayout_8 = QGridLayout(self.averageSampleFrame)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.singleAnalyzerLineRadio_2 = QRadioButton(self.averageSampleFrame)
        self.singleAnalyzerLineRadio_2.setObjectName(u"singleAnalyzerLineRadio_2")
        self.gridLayout_8.addWidget(self.singleAnalyzerLineRadio_2, 0, 0, 1, 1)
        self.singleAnalyzerScatterRadio_2 = QRadioButton(self.averageSampleFrame)
        self.singleAnalyzerScatterRadio_2.setObjectName(u"singleAnalyzerScatterRadio_2")
        self.gridLayout_8.addWidget(self.singleAnalyzerScatterRadio_2, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.averageSampleFrame, 2, 0, 1, 1)
        self.singleAnalyzerFrame = QFrame(self.radioFrame)
        self.singleAnalyzerFrame.setObjectName(u"singleAnalyzerFrame")
        self.singleAnalyzerFrame.setFrameShape(QFrame.StyledPanel)
        self.singleAnalyzerFrame.setFrameShadow(QFrame.Raised)
        self.gridLayout_9 = QGridLayout(self.singleAnalyzerFrame)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName(u"gridLayout_9")
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.averageAnalyzerScatterRadio_2 = QRadioButton(self.singleAnalyzerFrame)
        self.averageAnalyzerScatterRadio_2.setObjectName(u"averageAnalyzerScatterRadio_2")
        self.gridLayout_9.addWidget(self.averageAnalyzerScatterRadio_2, 0, 0, 1, 1)
        self.averageAnalyzerLineRadio_2 = QRadioButton(self.singleAnalyzerFrame)
        self.averageAnalyzerLineRadio_2.setObjectName(u"averageAnalyzerLineRadio_2")
        self.gridLayout_9.addWidget(self.averageAnalyzerLineRadio_2, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.singleAnalyzerFrame, 3, 0, 1, 1)
        self.singleSampleFrame = QFrame(self.radioFrame)
        self.singleSampleFrame.setObjectName(u"singleSampleFrame")
        self.singleSampleFrame.setFrameShape(QFrame.StyledPanel)
        self.singleSampleFrame.setFrameShadow(QFrame.Raised)
        self.gridLayout_7 = QGridLayout(self.singleSampleFrame)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.singleSampleLineRadio_2 = QRadioButton(self.singleSampleFrame)
        self.singleSampleLineRadio_2.setObjectName(u"singleSampleLineRadio_2")
        self.gridLayout_7.addWidget(self.singleSampleLineRadio_2, 0, 0, 1, 1)
        self.singleSampleScatterRadio_2 = QRadioButton(self.singleSampleFrame)
        self.singleSampleScatterRadio_2.setObjectName(u"singleSampleScatterRadio_2")
        self.gridLayout_7.addWidget(self.singleSampleScatterRadio_2, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.singleSampleFrame, 1, 0, 1, 1)
        self.labelFrame = QFrame(self.radioFrame)
        self.labelFrame.setObjectName(u"labelFrame")
        self.labelFrame.setFrameShape(QFrame.StyledPanel)
        self.labelFrame.setFrameShadow(QFrame.Raised)
        self.gridLayout_5 = QGridLayout(self.labelFrame)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.scatterTitle_2 = QLabel(self.labelFrame)
        self.scatterTitle_2.setObjectName(u"scatterTitle_2")
        self.scatterTitle_2.setMaximumSize(QSize(16777215, 30))
        self.gridLayout_5.addWidget(self.scatterTitle_2, 0, 0, 1, 1)
        self.linetitle_2 = QLabel(self.labelFrame)
        self.linetitle_2.setObjectName(u"linetitle_2")
        self.linetitle_2.setMaximumSize(QSize(16777215, 30))
        self.gridLayout_5.addWidget(self.linetitle_2, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.labelFrame, 0, 0, 1, 1)
        self.averageAnalyzerFrame = QFrame(self.radioFrame)
        self.averageAnalyzerFrame.setObjectName(u"averageAnalyzerFrame")
        self.averageAnalyzerFrame.setFrameShape(QFrame.StyledPanel)
        self.averageAnalyzerFrame.setFrameShadow(QFrame.Raised)
        self.gridLayout_10 = QGridLayout(self.averageAnalyzerFrame)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName(u"gridLayout_10")
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.averageSampleLineRadio_2 = QRadioButton(self.averageAnalyzerFrame)
        self.averageSampleLineRadio_2.setObjectName(u"averageSampleLineRadio_2")
        self.gridLayout_10.addWidget(self.averageSampleLineRadio_2, 0, 0, 1, 1)
        self.averageSampleScatterRadio_2 = QRadioButton(self.averageAnalyzerFrame)
        self.averageSampleScatterRadio_2.setObjectName(u"averageSampleScatterRadio_2")
        self.gridLayout_10.addWidget(self.averageSampleScatterRadio_2, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.averageAnalyzerFrame, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.radioFrame, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.baseFrame_2, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.baseFrame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Create new figure", None))
        self.classTitle.setText(QCoreApplication.translate("Dialog", u"Class", None))
        self.classCombo.setItemText(0, QCoreApplication.translate("Dialog", u"Normal", None))
        self.classCombo.setItemText(1, QCoreApplication.translate("Dialog", u"1", None))
        self.classCombo.setItemText(2, QCoreApplication.translate("Dialog", u"2", None))

        self.predQualTitle.setText(QCoreApplication.translate("Dialog", u"Prediction quality", None))
        self.predQualCombo.setItemText(0, QCoreApplication.translate("Dialog", u"Correct", None))
        self.predQualCombo.setItemText(1, QCoreApplication.translate("Dialog", u"All", None))
        self.predQualCombo.setItemText(2, QCoreApplication.translate("Dialog", u"Incorrect", None))
        self.predQualCombo.setItemText(3, QCoreApplication.translate("Dialog", u"False positive", None))
        self.predQualCombo.setItemText(4, QCoreApplication.translate("Dialog", u"False negative", None))

        self.plotTypeTitle.setText(QCoreApplication.translate("Dialog", u"Plot type", None))
        self.plotTypeCombo.setItemText(0, QCoreApplication.translate("Dialog", u"Comparison", None))
        self.plotTypeCombo.setItemText(1, QCoreApplication.translate("Dialog", u"Distribution", None))
        self.plotTypeCombo.setItemText(2, "")

        self.resetButton.setText(QCoreApplication.translate("Dialog", u"Reset", None))
        self.cancelButton.setText(QCoreApplication.translate("Dialog", u"Cancel", None))
        self.createButton.setText(QCoreApplication.translate("Dialog", u"Create", None))
        self.channelsTitle.setText(QCoreApplication.translate("Dialog", u"Channels", None))
        self.singleSampleCheckbox.setText(QCoreApplication.translate("Dialog", u"Single sample", None))
        self.averageSampleCheckbox.setText(QCoreApplication.translate("Dialog", u"Average sample over class", None))
        self.singleAnalyzerCheckbox.setText(QCoreApplication.translate("Dialog", u"Single analyzer score", None))
        self.averageAnalyzerCheckbox.setText(QCoreApplication.translate("Dialog", u"Average analyzer score", None))
        self.singleAnalyzerLineRadio_2.setText("")
        self.singleAnalyzerScatterRadio_2.setText("")
        self.averageAnalyzerScatterRadio_2.setText("")
        self.averageAnalyzerLineRadio_2.setText("")
        self.singleSampleLineRadio_2.setText("")
        self.singleSampleScatterRadio_2.setText("")
        self.scatterTitle_2.setText(QCoreApplication.translate("Dialog", u"Scatter", None))
        self.linetitle_2.setText(QCoreApplication.translate("Dialog", u"Line", None))
        self.averageSampleLineRadio_2.setText("")
        self.averageSampleScatterRadio_2.setText("")
    # retranslateUi

